server:
  # nginx default port ? 5000
  port: 5000
  max-http-header-size: 400000

spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - database
      - oauth2_authorization_server
      - oauth2_client_server
      - aws
      - apikey
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upload_path: ./naljava/files

init_data: false # 초기 데이터 초기화 여부 *false 권장
init_file_data: false # 이미지 업로드 여부 *false 권장

http_https: https://
server_domain: naljava.rn00n.com # 서버 TODO # 개설 안함.
service_domain: naljava.rn00n.com # 서버 TODO # 개설 안함.

bucket_url: https://rn00n-naljava.s3.ap-northeast-2.amazonaws.com # 서버 TODO # 개설 안함.
